services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    ports:
        - "9926:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    depends_on:
      - postgres
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=mealie2.antjrobles.tech
     # - OPENAI_BASE_URL=http://192.169.0.41:11434/v1
      - OPENAI_API_KEY=REDACTED
    # Database Settings
      - DB_ENGINE=postgres
      - POSTGRES_USER=mealie
      - POSTGRES_PASSWORD=mealie
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie
    restart: always
  postgres:
    image: postgres:15
    container_name: portgress_mealie
    restart: always
    volumes:
      - ./mealie-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mealie
      POSTGRES_USER: mealie

volumes:
  mealie-data:
    driver: local
  mealie-pgdata:
    driver: local
networks:
  default:
    name: shared-network
