---
version: "2.1"
services:
  cops:
    image: ghcr.io/linuxserver/cops:latest
    container_name: cops
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Madrid
    volumes:
      - /mnt/MIHDD/Appdata/cops/config:/config
      - /mnt/MIHDD/Appdata/calibre/config/library:/books
    ports:
      - 8773:80
    restart: always
