cadvisor:
    image: martadinata666/cadvisor:git
    container_name: cadvisor
    command: --raw_cgroup_prefix_whitelist=/docker/
    ports:
      - 8145:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
        - /dev/kmsg:/dev/kmsg
    restart: unless-stopped
    command:
      - '--docker_only=true'
      - '--housekeeping_interval=55s'
      - '--disable_metrics=disk,network,tcp,udp,percpu,sched,process'
