services:
  mkdocs:
    image: squidfunk/mkdocs-material
    container_name: mkdocs
    ports:
      - 8018:8000
    volumes:
      - ./:/docs
    stdin_open: true
    restart: always
    tty: true
networks: {}
