services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Madrid
      - SERVERURL=5.224.247.4
      - ALLOWEDIPS=0.0.0.0/0
      - SERVERPORT=51821  # Puerto diferente al del primer servidor
      - PEERS=4
      - PEERDNS=8.8.8.8
      - INTERNAL_SUBNET=10.13.14.0  # Una red interna diferente para evitar conflictos
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51821:51820/udp  # Puerto mapeado a la IP p√∫blica
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
