services:
  db:
    container_name: airtrail_db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    platform: linux/arm64
    restart: always
    env_file:
      - .env
    ports:
      - 3772:3000
    depends_on:
      - db
volumes:
  db_data:
