services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    environment:
      - PUID=1001
      - PGID=1001
    ports:
      - 8334:80
    volumes:
      - /:/srv
      - /home/antjrobles/appdata/filebrowser/filebrowser.db:/database/filebrowser.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
