services:
  n8n:
    container_name: n8n
    ports:
      - 5688:5678
    environment:
      - WEBHOOK_URL=https://n8n.antjrobles.tech
      - N8N_EDITOR_BASE_URL=https://n8n.antjrobles.tech
      - EXECUTIONS_PROCESS=main
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=smtp.gmail.com
      - N8N_SMTP_PORT=465
      - N8N_SMTP_USER=antjrobles
      - N8N_SMTP_PASS=qwhzcgpmtmgsbzvx
      - N8N_SMTP_SENDER=N8Ncontact@n8n.com
    volumes:
      - ./.n8n:/home/node/.n8n
    image: n8nio/n8n:latest
    restart: unless-stopped
