services:
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      glance.name: Beszel-Agent
      glance.icon: di:beszel
      glance.url: https://beszel.antjrobles.tech/
      glance.description: Servers Monitor
    environment:
      PORT: 45876
      KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIClyk0UXBW0ii3rlsPLnGD0iMVbClHD5347oH8d1o7/8"
      # FILESYSTEM: /dev/sda1 # set to the correct filesystem for disk I/O stats
