services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: REDACTED
      MYSQL_PASSWORD: REDACTED
      MYSQL_USER: vikunja
      MYSQL_DATABASE: vikunja
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u vikunja --password=REDACTED"]
      interval: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  vikunja:
    image: vikunja/vikunja:latest
    restart: unless-stopped
    container_name: vikunja
    environment:
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: REDACTED
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_REDIS_ENABLED: 1
      VIKUNJA_REDIS_HOST: redis:6379
      VIKUNJA_SERVICE_TIMEZONE: Europe/Madrid
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.antjrobles.tech/
      VIKUNJA_SERVICE_FRONTENDURL: http://192.168.0.32:3456/
      VIKUNJA_SERVICE_JWTSECRET: 1a2b3c4d5e6f7g8h9i0jKlMnOpQrStUvWxYzAbCdEfGhIjK
    volumes:
      - files:/app/vikunja/files
    ports:
      - 3456:3456
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  db:
  redis:
  files:
